- launch/simulation/simulation.launch
- machines/hero2.machine
Depends on https://github.com/tue-robotics/ed_object_models/pull/41 for object spawner.
> Small fixes

- launch/simulation/simulation.launch
Merge together with tue-robotics/ed_object_models#46
> Remove version number from gazebo world

- scripts/hero1-battery-conversion.service
- scripts/hero1-monitor.service
- scripts/hero1-start.service
- scripts/hero2-openpose.service
- scripts/hero2-rgbd-shm-server.service
- scripts/hero2-upower-ros.service
Service keep restarting till connecting to roscore.
> Services restart

- launch/hero_bringup.launch
- parameters/manipulation/head_server.yaml
* Added remapping to neck measurement topic to subscribe to joint states
* Added neck_pan_joint and neck_tilt_joint as parameters
Make sure to merge with https://github.com/tue-robotics/head_ref/pull/13 and https://github.com/tue-robotics/hero_bridge/pull/13
> fix(head)Fixed topics and params for (hero) head ref

- launch/hero_bringup.launch
Merge together with tue-robotics/rgbd#26
> RGBD refactor

- launch/simulation/gazebo.launch
I don't know when this started. I also didn't experience any problems yet, but it produced errors, red print. So that should be solved right now.
> fix gazebo control param ns

- launch/hero_bringup.launch
Merge this together with https://github.com/tue-robotics/tue-env-targets/pull/159 or any other PR which introduces the `hsrb_moveit` git targets.
> use hsrb_moveit_config from real package

- scripts/services/hero2-demo/hero2-demo-openpose.service
- scripts/services/hero2/hero2-openpose.service
Merge together/after https://github.com/tue-robotics/image_recognition/pull/116
Part 2 of https://github.com/tue-robotics/tue_robocup/issues/1045
> reconnect openpose node on HERO2

- scripts/services/hero2-demo/hero2-demo-upower-ros.service
- scripts/services/hero2/hero2-upower-ros.service
Merge togerther/after https://github.com/tue-robotics/upower_ros/pull/3
Part 1 of https://github.com/tue-robotics/tue_robocup/issues/1045
> reconnect upower node on HERO2

- parameters/hardware/sensors/base_laser_filters_parameters.yaml
Also laser points on a wall further away were removed, as these also are close to being behind each other. Or walls closer, but the direction of the wall being close to the direction of the laser beams
> Less aggressive laser filtering

- launch/hero_bringup.launch
* Needs testing
* Merge together with https://github.com/tue-robotics/tue_robocup/pull/1101 and https://github.com/tue-robotics/hero_bridge/pull/26
> cleanup()Removed lights bridge

- launch/hero_bringup.launch
Changes in launch file to use the `ros_to_rgbd` nodelet.
Merge together with https://github.com/tue-robotics/rgbd/pull/40
> ros_to_rgbd nodelet

- parameters/tools/rviz_config.rviz
> Fix rviz topics

- launch/state_machines/free_mode_amcl.launch
- parameters/localization/amcl.yaml
- parameters/world_modeling/world_model_amcl.yaml
- parameters/world_modeling/world_model_plugin_localization.yaml
Merge together with https://github.com/tue-robotics/ed_localization/pull/15
The new launch file is to run free_mode with ROS AMCL instead of ED AMCL.
As the implementation of ED AMCL is updated in the PR mentioned above, the parameters need to be updated.
> AMCL parameters

- parameters/world_modeling/world_model.yaml
- parameters/world_modeling/world_model_demo_extern.yaml
- parameters/world_modeling/world_model_learn_objects.yaml
- parameters/world_modeling/world_model_plugin_gui_server.yaml
- parameters/world_modeling/world_model_plugin_laser.yaml
- parameters/world_modeling/world_model_plugin_laser_clearer.yaml
- parameters/world_modeling/world_model_plugin_localization.yaml
- parameters/world_modeling/world_model_plugin_navigation.yaml
- parameters/world_modeling/world_model_plugin_people_recognition.yaml
- parameters/world_modeling/world_model_plugin_perception.yaml
- parameters/world_modeling/world_model_plugin_rgbd.yaml
- parameters/world_modeling/world_model_plugin_rgbd_navigation.yaml
- parameters/world_modeling/world_model_plugin_robot.yaml
- parameters/world_modeling/world_model_plugin_tf.yaml
Merge with: https://github.com/tue-robotics/ed/pull/130
> Use new ED pluginlib

- launch/state_machines/challenge_rips.launch
Merge together with https://github.com/tue-robotics/tue_robocup/pull/1182
> (rips) exec has been renamed

- scripts/services/hero1-demo/hero1-demo-ntpdate.service
- scripts/services/hero1/hero1-ntpdate.service
@ar13pit what will happen when it keeps on failing? When will it stop to restart?
> Fix(ntpdate)

- parameters/navigation/navscan.yaml
Merge before/together with https://github.com/tue-robotics/depthimage_to_navscan/pull/12
> Add new parameters for depthimage_to_navscan

- parameters/navigation/navscan.yaml
Related to https://github.com/tue-robotics/depthimage_to_navscan/pull/13
> Limit navscan rate to 10 Hz

- launch/start.launch
- scripts/services/hero1-demo/hero1-demo-roscore.service
- scripts/services/hero1/hero1-roscore.service
One of our BEP students will be using the handcamera next semester. And its useful in general.
> Start the hand camera

- launch/hero_bringup.launch
Merge after https://github.com/tue-robotics/hmi/pull/41
> feat: Add qr decoder image topic as arg
